# Generated by Django 6.0.3 on 2026-03-12 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hearing_type', models.CharField(choices=[('hearing', 'Hearing'), ('meeting', 'Meeting'), ('deadline', 'Deadline'), ('trial', 'Trial')], default='hearing', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('hearing_date', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, help_text='Expected duration of hearing', null=True)),
                ('court', models.CharField(max_length=200)),
                ('judge', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_1h_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hearings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hearing_date'],
                'indexes': [models.Index(fields=['hearing_date'], name='calendar_ap_hearing_39da5e_idx'), models.Index(fields=['status'], name='calendar_ap_status_cb7bf2_idx')],
            },
        ),
    ]
