# Generated by Django 6.0.3 on 2026-04-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing',
            name='reminder_1h_sent',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='reminder_24h_sent',
        ),
        migrations.AddField(
            model_name='hearing',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
