# Generated by Django 6.0.3 on 2026-03-13 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('clients', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('case', 'Case Activity'), ('file', 'File Activity'), ('client', 'Client Activity'), ('system', 'System Activity'), ('user', 'User Activity')], max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('username', models.CharField(blank=True, max_length=150)),
                ('case_title', models.CharField(blank=True, max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('document_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('info', 'Info')], default='info', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.case')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='activities__timesta_891f04_idx'), models.Index(fields=['type'], name='activities__type_a1420f_idx'), models.Index(fields=['user'], name='activities__user_id_a9ae64_idx')],
            },
        ),
    ]
